### ISSUE TITLE
Cloning repo from http://ip:port causes HgCacheInconsistentError

### ISSUE THREAD

**Issue by Artalus** [trassir/hg-cache#9]
```
iivanov [ py2] /tmp $ hg --config extensions.hgcache=/work/hg-cache/ clone http://172.16.16.147:9999
HGCACHE: cache at /tmp/hgcache is empty, populate using clone of http://172.16.16.147:9999
** Unknown exception encountered
  File "/work/hg-cache/cacheutils.py", line 65, in initialize_cache
    cache_dir=cache_dir))
hgext_hgcache.cacheutils.HgCacheInconsistentError: cache in /tmp/hgcache is from irrelevant repo 'http://172.16.16.147:9999/' - expected 'http://172.16.16.147:9999'
```
Seems that in `.hgrc` the path is stored with trailing `/` in some cases

**Comment by worldemar** [comment]
looks like having `/` as last character in URL is causing this, not `http` schema or usage of `ip:port` instead of domain name.

Maybe extra slash at the end should not be considered a _difference_ for an URL.
I wonder how many other things in URL could cause it to look different when compared as a plain string.

**Comment by worldemar** [comment]
Looks like mercurial [does not store url as-is](https://www.mercurial-scm.org/repo/hg/file/1f8f215219ff/mercurial/hg.py#l884) and has [it's own implementation](https://www.mercurial-scm.org/repo/hg/file/1f8f215219ff/mercurial/util.py#l2955) of url handling routines.

Since implementaion itself is not publicly accessible (as in "we cannot just import it and use it to compare urls"), I would resort to "let's just ignore slashes at the end" approach.

The annoying part there - extra slashes seem to only happen in "ip:port (no path)"-type urls which is a pain to write a correct testcase for.
